baseURL = 'https://moeed.com/'
languageCode = 'en-us'
title = 'Moeed Ahmad'
theme = "PaperMod"

[markup.goldmark.renderer]
unsafe = true

[menu]

# 1. HOME
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

# 2. WORK (Top Level Parent)
[[menu.main]]
  identifier = "work"
  name = "Work"
  url = "/work/"
  weight = 20

# 3. POSTS
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 30

# 4. ABOUT
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 80

# 5. CONTACT
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 90